apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: api-gateway
        image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: TICKET_SERVICE_URL
          value: "{{ .Values.apiGateway.env.ticketServiceUrl }}"
        - name: JWT_SECRET
          {{- if .Values.secrets.create }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "service-hub.fullname" .)) }}
              key: jwt-secret
          {{- else }}
          value: "{{ .Values.secrets.jwtSecret }}"
          {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.apiGateway.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: 8000
  selector:
    app: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
