apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.notificationService.replicas }}
  selector:
    matchLabels:
      app: notification-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: notification-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: notification-service
        image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8002
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.notificationService.env.kafkaBootstrapServers | default .Values.global.kafka.bootstrapServers }}"
        - name: KAFKA_TOPIC
          value: "{{ .Values.global.kafka.topic }}"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.notificationService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notificationService.service.type }}
  ports:
  - port: {{ .Values.notificationService.service.port }}
    targetPort: 8002
  selector:
    app: notification-service
    app.kubernetes.io/instance: {{ .Release.Name }}
