{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "service-hub.fullname" .)) }}
  labels:
    {{- include "service-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: "{{ .Values.secrets.jwtSecret }}"
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  db-password: "{{ .Values.secrets.dbPassword }}"
  {{- end }}
{{- end }}
