apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-hub.fullname" . }}-kafka
  labels:
    app: kafka
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kafka
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      enableServiceLinks: false # avoid injected KAFKA_PORT env overriding listener config
      hostname: kafka
      containers:
      - name: kafka
        image: "{{ .Values.kafka.image }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "{{ .Values.kafka.brokerId }}"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        resources:
          {{- toYaml .Values.kafka.resources | nindent 10 }}
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
      volumes:
      - name: kafka-data
        {{- if .Values.kafka.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "service-hub.fullname" . }}-kafka
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- if .Values.kafka.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "service-hub.fullname" . }}-kafka
  labels:
    app: kafka
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  ports:
  - name: external
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
