apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  labels:
    app: ticket-service
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ticketService.replicas }}
  selector:
    matchLabels:
      app: ticket-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: ticket-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: ticket-service
        image: "{{ .Values.ticketService.image.repository }}:{{ .Values.ticketService.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "{{ .Values.ticketService.env.db.host }}"
        - name: DB_PORT
          value: "{{ .Values.ticketService.env.db.port }}"
        - name: DB_NAME
          value: "{{ .Values.ticketService.env.db.name }}"
        - name: DB_USER
          value: "{{ .Values.ticketService.env.db.user }}"
        - name: DB_PASSWORD
          {{- if .Values.secrets.create }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "service-hub.fullname" .)) }}
              key: db-password
          {{- else }}
          value: "{{ .Values.secrets.dbPassword }}"
          {{- end }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.ticketService.env.kafkaBootstrapServers | default .Values.global.kafka.bootstrapServers }}"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.ticketService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  labels:
    app: ticket-service
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ticketService.service.type }}
  ports:
  - port: {{ .Values.ticketService.service.port }}
    targetPort: 8001
  selector:
    app: ticket-service
    app.kubernetes.io/instance: {{ .Release.Name }}
