apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-hub.fullname" . }}-zookeeper
  labels:
    app: zookeeper
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: zookeeper
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: zookeeper
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: zookeeper
        image: "{{ .Values.zookeeper.image }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper:2888:3888"
        resources:
          {{- toYaml .Values.zookeeper.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    {{- include "service-hub.labels" . | nindent 4 }}
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
